import type { EndpointDefinition } from "@/types/config"

export const ZONE_QUERY: EndpointDefinition = {
  id: "zone-query",
  method: "POST",
  url: "/cvservlet/zonequeries",
  params: ["physicalId", "expandLevel"],
  payload: {
    root_path_physicalid: ["{{physicalId}}"],
    select_bo: [
      "type",
      "physicalId",
      "name",
      "revision",
      "ds6w:label",
      "description",
      "ds6w:policy",
      "ds6w:modified",
      "ds6w:created",
      "current",
      "cestamp",
      "owner",
      "ds6w:responsible",
      "ds6w:manufacturable",
      "ds6wg:EnterpriseExtension.V_PartNumber",
      "project",
      "organization",
      "ds6w:kind",
      "ds6w:reserved",
      "ds6w:reservedby",
      "ds6w:cadMaster",
      "ds6wg:PLMInstance.PLM_ExternalID",
      "ds6wg:PLMReference.V_isLastVersion",
      "ds6wg:WCGEquivalentDeclaredInertiaExt.V_WCG_Declared_COGx",
      "ds6wg:WCGEquivalentDeclaredInertiaExt.V_WCG_Declared_COGy",
      "ds6wg:WCGEquivalentDeclaredInertiaExt.V_WCG_Declared_COGz",
      "ds6wg:WCGEquivalentComputedExt.V_WCG_COGz",
      "ds6wg:WCGEquivalentComputedExt.V_WCG_COGy",
      "ds6wg:WCGEquivalentComputedExt.V_WCG_COGx",
      "ds6w:declaredWeight",
      "ds6w:Weight",
    ],
    label: "customZoneQuery",
    expand_iter: "{{expandLevel}}",
    select_rel: [
      "ds6w:type",
      "physicalId",
      "name",
      "ds6w:label",
      "description",
      "modified",
      "ds6w:created",
      "ds6wg:LPAbstractInstance.V_IsFixedInstance",
      "ds6w:description",
      "matrixTxt",
      "cestamp",
      "ro.plminstance.V_treeorder",
      "ds6wg:SynchroEBOMExt.V_InEBOMUser",
    ],
    compute_select_bo: ["icon", "thumbnail_2d"],
    fcs_url_mode: "REDIRECT",
    no_type_filter_rel: ["XCADBaseDependency"],
  },
  responseMapping: {
    physicalId: "id",
    label: "title",
    project: "collabspace",
    current: "state",
    manufacturable: "isManufacturable",
    "PLMReference.V_isLastVersion": "isLastVersion",
    "PLMInstance.PLM_ExternalID": "PLM_ExternalID",
    "EnterpriseExtension.V_PartNumber": "partNumber",
    "LPAbstractInstance.V_IsFixedInstance": "isFixedInstance",
    "ds6wg:WCGEquivalentDeclaredInertiaExt.V_WCG_Declared_COGx": "V_WCG_Declared_COGx",
    "ds6wg:WCGEquivalentDeclaredInertiaExt.V_WCG_Declared_COGy": "V_WCG_Declared_COGy",
    "ds6wg:WCGEquivalentDeclaredInertiaExt.V_WCG_Declared_COGz": "V_WCG_Declared_COGz",
    "ds6wg:WCGEquivalentComputedExt.V_WCG_COGz": "V_WCG_COGz",
    "ds6wg:WCGEquivalentComputedExt.V_WCG_COGy": "V_WCG_COGy",
    "ds6wg:WCGEquivalentComputedExt.V_WCG_COGx": "V_WCG_COGx",
  },
  defaultValues: {
    "dseno:EnterpriseAttributes": {},
    "dseng:EnterpriseReference": { partNumber: "" },
    kind: "",
    V_WCG_Declared_COGx: "0",
    V_WCG_Declared_COGy: "0",
    V_WCG_Declared_COGz: "0",
    V_WCG_COGz: "0",
    V_WCG_COGy: "0",
    V_WCG_COGx: "0",
    declaredWeight: "0",
    Weight: "0",
    PLM_ExternalID: "",
    reservedby: "",
  },
}

export const DEFAULT_ICONS: Record<string, string> = {
  VPMReference: "/snresources/images/icons/large/I_VPMNavProduct108x144.png",
  "3DPart": "/snresources/images/icons/large/I_3DPart108x144.png",
  "3DShape": "/snresources/images/icons/large/I_Part108x144.png",
  Drawing: "/snresources/images/icons/large/I_VPMNavDrawing108x144.png",
}
