/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XenRouteImport } from './routes/xen'
import { Route as ChangeRouteImport } from './routes/change'
import { Route as IndexRouteImport } from './routes/index'

const XenRoute = XenRouteImport.update({
  id: '/xen',
  path: '/xen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRoute = ChangeRouteImport.update({
  id: '/change',
  path: '/change',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change': typeof ChangeRoute
  '/xen': typeof XenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change': typeof ChangeRoute
  '/xen': typeof XenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change': typeof ChangeRoute
  '/xen': typeof XenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/change' | '/xen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/change' | '/xen'
  id: '__root__' | '/' | '/change' | '/xen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeRoute: typeof ChangeRoute
  XenRoute: typeof XenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xen': {
      id: '/xen'
      path: '/xen'
      fullPath: '/xen'
      preLoaderRoute: typeof XenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change': {
      id: '/change'
      path: '/change'
      fullPath: '/change'
      preLoaderRoute: typeof ChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeRoute: ChangeRoute,
  XenRoute: XenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
