/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XenRouteImport } from './routes/xen'
import { Route as CaRouteImport } from './routes/ca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaNodeIdRouteImport } from './routes/ca/$nodeId'

const XenRoute = XenRouteImport.update({
  id: '/xen',
  path: '/xen',
  getParentRoute: () => rootRouteImport,
} as any)
const CaRoute = CaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaNodeIdRoute = CaNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => CaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ca': typeof CaRouteWithChildren
  '/xen': typeof XenRoute
  '/ca/$nodeId': typeof CaNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ca': typeof CaRouteWithChildren
  '/xen': typeof XenRoute
  '/ca/$nodeId': typeof CaNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ca': typeof CaRouteWithChildren
  '/xen': typeof XenRoute
  '/ca/$nodeId': typeof CaNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ca' | '/xen' | '/ca/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ca' | '/xen' | '/ca/$nodeId'
  id: '__root__' | '/' | '/ca' | '/xen' | '/ca/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaRoute: typeof CaRouteWithChildren
  XenRoute: typeof XenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xen': {
      id: '/xen'
      path: '/xen'
      fullPath: '/xen'
      preLoaderRoute: typeof XenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca': {
      id: '/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof CaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/$nodeId': {
      id: '/ca/$nodeId'
      path: '/$nodeId'
      fullPath: '/ca/$nodeId'
      preLoaderRoute: typeof CaNodeIdRouteImport
      parentRoute: typeof CaRoute
    }
  }
}

interface CaRouteChildren {
  CaNodeIdRoute: typeof CaNodeIdRoute
}

const CaRouteChildren: CaRouteChildren = {
  CaNodeIdRoute: CaNodeIdRoute,
}

const CaRouteWithChildren = CaRoute._addFileChildren(CaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaRoute: CaRouteWithChildren,
  XenRoute: XenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
